"""
Django settings for back_end_django project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config ##############CODIGO 9############################
from datetime import timedelta ##############C############################
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g1xls^+wywr45&@*-pxt*t#ab1oe3w*3dj@)eg+80lwgkyt%a1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
####################FIGRUA 4############################
INSTALLED_APPS = [
    "gestion_usuarios.apps.GestionUsuariosConfig",
    "gestion_productos.apps.GestionProductosConfig", #PRACTICA 5
    "autentificacion.apps.AutentificacionConfig", #PRACTICA 6
    "rest_framework_simplejwt.token_blacklist", #PRACTICA 6
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    'rest_framework',
    'corsheaders',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'back_end_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'back_end_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": config("DATABASE_ENGINE"),
        "NAME": config("DATABASE_NAME"),
        "USER": config("DATABASE_USER"),
        "PASSWORD": config("DATABASE_PASSWORD"),
        "HOST": config("DATABASE_HOST"),
        "PORT": config("DATABASE_PORT"),
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
##################################Codigo 5 PRACTICA6 ##################################
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

    # Rotación de refresh tokens
    'ROTATE_REFRESH_TOKENS': True,

    # Enviar refresh token usado a blacklist
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',

    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': (
        'rest_framework_simplejwt.tokens.AccessToken',
    ),

    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}
##################Codigo 8 PRACTICA6 ##################
SWAGGER_SETTINGS = {

    # Desactiva el inicio de sesión mediante cookies de Django
    'USE_SESSION_AUTH': False,

    # Se evita que Swagger realice validaciones externas
    # que puedan generar errores
    'VALIDATOR_URL': None,

    # Definición del esquema de autenticación Bearer
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': (
                'Encabezado para autenticación JWT con esquema Bearer. '
                'Ejemplo: "Bearer {token}"'
            ),
        }
    },
}
# ─────────────────────────────────────────
# CORS codigo 4 practica 7
# ─────────────────────────────────────────
# Orígenes permitidos (ajusta según tu frontend)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",   
    "http://localhost:4200",   
    "http://127.0.0.1:3000",
]

# Permite enviar cookies y encabezados de autorización
CORS_ALLOW_CREDENTIALS = True

# Métodos HTTP que acepta la API desde el frontend
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# Encabezados que el frontend puede enviar
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",       # ← necesario para enviar el JWT
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
################codigo 6 PRACTICA 7###########################################
# ─────────────────────────────────────────
# LOGGING — Logs técnicos
# ─────────────────────────────────────────
import os

LOGS_DIR = BASE_DIR / 'logs'
os.makedirs(LOGS_DIR, exist_ok=True)   # crea la carpeta si no existe

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # conserva los loggers internos de Django

    # ── Formatos ──────────────────────────────────────────────────────────────
    'formatters': {
        # Formato detallado para archivos
        'tecnico_detallado': {
            'format': '[{asctime}] [{levelname}] [{name}] [{module}:{lineno}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        # Formato corto para consola
        'consola_simple': {
            'format': '[{levelname}] {name}: {message}',
            'style': '{',
        },
        #se agrega para logs de auditoria. #NUEVO
        'auditoria_formato': {
            'format': '[{asctime}] [AUDITORIA] [Usuario: {message}]',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        }
    },

    #filtros
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',  # solo activo con DEBUG=True
        },
    },

    # ── Handlers 
    'handlers': {
        # Consola — solo en desarrollo
        'consola': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'consola_simple',
            'filters': ['require_debug_true'],
        },
        # Archivo rotativo para errores técnicos
        'archivo_tecnico': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'tecnico.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB por archivo
            'backupCount': 5,              # conserva hasta 5 archivos históricos
            'formatter': 'tecnico_detallado',
            'encoding': 'utf-8',
        },
        # Archivo rotativo para mensajes DEBUG e INFO
        'archivo_debug': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'debug.log',
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 3,
            'formatter': 'tecnico_detallado',
            'encoding': 'utf-8',
        },
            # Handler específico para logs de auditoría #NUEVO
        'archivo_auditoria': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'auditoria.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB por archivo
            'backupCount': 10,             # conserva hasta 10 archivos históricos
            'formatter': 'auditoria_formato',
            'encoding': 'utf-8',
        }
    },

    # ── Loggers ───────────────────────────────────────────────────────────────
    'loggers': {
        # Logger raíz de Django (errores internos del framework)
        'django': {
            'handlers': ['consola', 'archivo_tecnico'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Peticiones HTTP (cada request que llega al servidor)
        'django.request': {
            'handlers': ['archivo_tecnico'],
            'level': 'WARNING',  # registra 4xx y 5xx automáticamente
            'propagate': False,
        },
        # Consultas a la base de datos
        'django.db.backends': {
            'handlers': ['archivo_debug'],
            'level': 'DEBUG',
            'propagate': False,
            'filters': ['require_debug_true'],  # solo en desarrollo
        },
        # Logger propio de la aplicación — usado en las views
        'back_end_django': {
            'handlers': ['consola', 'archivo_tecnico', 'archivo_debug'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Logger de gestion_usuarios
        'gestion_usuarios': {
            'handlers': ['consola', 'archivo_tecnico', 'archivo_debug'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Logger de gestion_productos
        'gestion_productos': {
            'handlers': ['consola', 'archivo_tecnico', 'archivo_debug'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Logger de auditoría #NUEVO
        'auditoria': {
            'handlers': ['archivo_auditoria', 'consola'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}