# Generated by Django 5.2.4 on 2025-07-24 07:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Administrador del sistema', 'Administrador del sistema'), ('Jefe del Departamento de Almacenes', 'Jefe del Departamento de Almacenes'), ('Segundo encargado del Departamento de Almacenes', 'Segundo encargado del Departamento de Almacenes'), ('Jefe del Almacén de Ropería', 'Jefe del Almacén de Ropería'), ('Segundo encargado del Almacén de Ropería', 'Segundo encargado del Almacén de Ropería'), ('Jefe del Almacén de Víveres', 'Jefe del Almacén de Víveres'), ('Segundo encargado del Almacén de Víveres', 'Segundo encargado del Almacén de Víveres'), ('Jefe del Almacén de Farmacia', 'Jefe del Almacén de Farmacia'), ('Segundo encargado Almacén de Farmacia', 'Segundo encargado Almacén de Farmacia'), ('Capturista de entradas', 'Capturista de entradas'), ('Capturista de salidas', 'Capturista de salidas'), ('Solicitante', 'Solicitante')], default='Solicitante', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('signing_password', models.CharField(max_length=255)),
                ('last_login_IP', models.GenericIPAddressField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('first_lastname', models.CharField(max_length=50)),
                ('second_lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('curp', models.CharField(max_length=18)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=255, null=True)),
                ('address_cat_nacionalidad_id', models.BigIntegerField(blank=True, null=True)),
                ('address_cat_entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('address_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address_neighborhood', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_number', models.CharField(blank=True, max_length=25, null=True)),
                ('address_interior_number', models.CharField(blank=True, max_length=25, null=True)),
                ('address_complement', models.TextField(blank=True, null=True)),
                ('job_position', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_number', models.CharField(blank=True, max_length=255, null=True)),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_by', models.ForeignKey(blank=True, help_text='Usuario que desactivó este usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuario que eliminó lógicamente el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('restored_by', models.ForeignKey(blank=True, help_text='Usuario que restauró el registro eliminado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_by_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('unblocked_by', models.ForeignKey(blank=True, help_text='Usuario que reactivó este usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unblocked_users', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que actualizó por última vez el registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
