# Generated by Django 5.2.4 on 2025-07-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='blocked_by',
            new_name='blocked_by_id',
        ),
    ]
