# Generated by Django 5.2.4 on 2025-07-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_blocked_by_user_blocked_by_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='blocked_by_id',
            new_name='blocked_by',
        ),
    ]
