# Generated by Django 5.2.4 on 2025-07-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_blocked_by_id_user_blocked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
