name: Scan code

on:
  push:
    branches:
       - development

jobs:
  scan:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345678
          POSTGRES_DB: test
        options: >-
          --health-cmd="pg_isready -U postgres -d test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Generate keys
        run: |
          mkdir -p keys
          openssl genrsa -out keys/private.pem 2048
          openssl rsa -in keys/private.pem -pubout -out keys/public.pem
      
      - name: Generate env file
        run: bash .github/scripts/env_test.sh '${{ secrets.SECRET_KEY }}'
      
      - name: Run Tests
        run: |
          export $(cat .env | xargs)
          pytest --cov=. --cov-report=xml --cov-report=term

      - name: Scan
        uses: SonarSource/sonarqube-scan-action@v5.3.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    